### PR TITLE
Set kitchen.yml to use a specific version

### PR DESCRIPTION
**Pull request by drenalin23**
# What
This forces kitchen to a specific version, which matches our current target for the mmi teams.

### CODE REVIEW

**Comment by SudoBasher** [comment]
Did some checking:

https://docs.chef.io/release_notes.html

**Comment by SudoBasher** [comment]
Did some checking:

https://docs.chef.io/config_yml_kitchen.html
https://docs.chef.io/release_notes.html
https://github.com/chef/chef/blob/master/CHANGELOG.md

Syntax declaration looks good.

Matching target versions for mmi teams sounds like good practice.

:+1: 

Shall we set a version tag after the merge, and then update the chef repo?

```
chef/Berksfile
56:cookbook 'metrics-filebeat', git: 'https://github.com/mmi-cookbooks/metrics-filebeat.git', tag: '0.2.2'

chef/Berksfile.lock
79:  metrics-filebeat
80:    git: https://github.com/mmi-cookbooks/metrics-filebeat.git
237:  metrics-filebeat (0.2.2)
```

**Comment by drenalin23** [comment]
@SudoBasher -
We don't need to bump the version as this change doesn't affect end nodes, it will only affect how tests run (getting kitchen/travis to use the higher version of Chef).  Then this change will get rolled up next time there is a change that needs to get out to nodes and needs to get versioned.  Changes to tests, and ancillary files don't need to be versioned if they won't change the behavior of a node in prod.

**Comment by SudoBasher** [comment]
:+1:

**Pull request merged**
